version: '3.8'
services:
  flask-app:
    build: ./flask-app
    command: gunicorn app:app --bind 0.0.0.0:8000
    volumes:
      - ./flask-app:/app
    depends_on:
      - mysql
    networks:
      - app-network
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DB: flaskdb

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flaskdb
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
