version: '3.8'
services:
  node-app:
    build: ./node-app
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://mongo:27017/nodeapp
      REDIS_URL: redis://redis:6379
    depends_on:
      - mongo
      - redis
    networks:
      - app-network

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
